language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "radixdlt-github"
jdk:
- oraclejdk8
jobs:
  include:
  - stage: test
    script:
    - "./gradlew test jacocoTestReport sonarqube"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"